name: Explore runners

on:
    push:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing on Ubuntu"
  
  test-windows:
    runs-on: windows-latest
    steps:
      - run: echo "Testing on Windows"
  
  test-macos:
    runs-on: macos-latest
    steps:
      - run: echo "Testing on macOS"
